apiVersion: v1
kind: Pod
metadata:
  name: dynamic-dns
  namespace: kube-system
spec:
  containers:
  - image: sjmayotte/route53-dynamic-dns:latest
    name: dynamic-dns
    env:
     - name: ROUTE53_HOSTED_ZONE_ID
       value: Z05605701ECX0UCEOKZBS
     - name: ROUTE53_DOMAIN
       value: traefik.staging.whereisdana.today
     - name: ROUTE53_TYPE
       value: A
     - name: ROUTE53_TTL
       value: '300'

    #TODO: might be nice to send this email one day
     - name: SEND_EMAIL_SES
       value: 'false'
     - name: SES_TO_ADDRESS
       value: 'false'
     - name: SES_FROM_ADDRESS
       value: 'false'
     - name: UPDATE_FREQUENCY
       value: '60000' # 1 minute

     - name: AWS_REGION
       value: us-east-1
     - name: AWS_ACCESS_KEY_ID
       value: TODO
     - name: AWS_SECRET_ACCESS_KEY
       value: TODO

    resources:
      limits:
        cpu: 1
        memory: 100M
      requests:
        cpu: 1
        memory: 100M
    volumeMounts:
      - name: aws-credentials
        mountPath: "/root/.aws/"
        readOnly: true
  volumes:
    - name: aws-credentials
      secret:
        secretName: external-dns-user-g7dmf4bm9c
