apiVersion: v1
kind: Service
metadata:
  name: obs
spec:
  type: ClusterIP
  selector:
    app: obs
  ports:
    - name: vnc
      port: 5900
      targetPort: vnc
    - name: websocket
      port: 4455
      targetPort: websocket
