apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pvc.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: vlc-server
  app.kubernetes.io/part-of: tripbot
