apiVersion: batch/v1
kind: Job
metadata:
  name: tripbot-migrate
spec:
  ttlSecondsAfterFinished: 3600
  backoffLimit: 6
  template:
    metadata:
      labels:
        app: tripbot-migrate
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: adanalife/tripbot:latest
          imagePullPolicy: Always
          command: ["migrate"]
          args:
            - "-path"
            - "/migrations"
            - "-database"
            - "postgres://$(DATABASE_USER):$(DATABASE_PASS)@$(DATABASE_HOST):5432/$(DATABASE_DB)?sslmode=disable"
            - "up"
          envFrom:
            - configMapRef:
                name: tripbot-config
            - secretRef:
                name: tripbot-secret
