name: Apply Terraform

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the deployment environment'
        required: true
        type: choice
        options:
          - prod-1
          - stage-1
          - core
        default: stage

jobs:
  apply:
    runs-on: ubuntu-latest
    name: Apply terraform configuration
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        #TODO: update the script so we dont _have_ to pass in a terraform path
      - run: ./.github/scripts/set-deploy-env.sh terraform/${{ github.event.inputs.environment }}
        env:
          CI_CORE_AWS_ACCESS_KEY_ID: ${{ secrets.CI_CORE_AWS_ACCESS_KEY_ID }}
          CI_CORE_AWS_SECRET_ACCESS_KEY: ${{ secrets.CI_CORE_AWS_SECRET_ACCESS_KEY }}
          CI_PROD_AWS_ACCESS_KEY_ID: ${{ secrets.CI_PROD_AWS_ACCESS_KEY_ID }}
          CI_PROD_AWS_SECRET_ACCESS_KEY: ${{ secrets.CI_PROD_AWS_SECRET_ACCESS_KEY }}
          CI_STAGE_AWS_ACCESS_KEY_ID: ${{ secrets.CI_AWS_ACCESS_KEY_ID }}
          CI_STAGE_AWS_SECRET_ACCESS_KEY: ${{ secrets.CI_AWS_SECRET_ACCESS_KEY }}
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: CITerraformRole
      - name: Check for drift
        uses: dflook/terraform-apply@v1
        with:
          path: terraform/${{ github.event.inputs.environment }}
