name: Apply Terraform

on:
  # trigger with PR comment
  # issue_comment:
  #   types:
  #     - created
  # manually trigger build
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the deployment environment'
        required: true
        type: choice
        default: stage-1
        options:
          - prod-1
          - stage-1
          - core

jobs:
  apply:
    runs-on: ubuntu-latest
    name: Apply terraform configuration
    env:
      # required in order to comment on PRs
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      # - name: Debug Event Payload
      #   run: echo "${{ toJson(github.event) }}"
      # - name: Determine what to check out
      #   run: |
      #     if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
      #       if [ "${{ github.event.inputs.branch }}" != "" ]; then
      #         echo "ref=${{ github.event.inputs.branch }}" >> $GITHUB_ENV
      #       else
      #         echo "ref=${{ github.ref }}" >> $GITHUB_ENV
      #       fi
      #     elif [ "${{ github.event_name }}" == "issue_comment" ]; then
      #       if [ -n "${{ github.event.issue.pull_request.head.ref }}" ]; then
      #         #TODO: use https://github.com/dflook/terraform-github-actions/tree/main/terraform-apply#issue_comment
      #         echo "ref=${{ github.event.issue.pull_request.head.ref }}" >> $GITHUB_ENV
      #       else
      #         echo "Unsupported trigger without PR branch."
      #         exit 1
      #       fi
      #     fi

      - uses: actions/checkout@v4
        # with:
        #   ref: ${{ env.ref }}

      - name: Determine terraform dir
        shell: bash
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "terraform_dir=terraform/${{ github.event.inputs.environment }}" >> $GITHUB_ENV
          # elif [[ "${{ github.event.comment.body }}" =~ ^/apply ]]; then
          #   short_env=$(echo "${{ github.event.comment.body }}" | cut -d' ' -f2)
          #   echo "terraform_dir=terraform/$short_env" >> $GITHUB_ENV
          else
            echo "Unsupported trigger source."
            exit 1
          fi
        #TODO: update the script so we dont _have_ to pass in a terraform path
      - run: ./.github/scripts/set-deploy-env.sh ${{ env.terraform_dir }}
        env:
          CI_CORE_AWS_ACCESS_KEY_ID: ${{ secrets.CI_CORE_AWS_ACCESS_KEY_ID }}
          CI_CORE_AWS_SECRET_ACCESS_KEY: ${{ secrets.CI_CORE_AWS_SECRET_ACCESS_KEY }}
          CI_PROD_AWS_ACCESS_KEY_ID: ${{ secrets.CI_PROD_AWS_ACCESS_KEY_ID }}
          CI_PROD_AWS_SECRET_ACCESS_KEY: ${{ secrets.CI_PROD_AWS_SECRET_ACCESS_KEY }}
          CI_STAGE_AWS_ACCESS_KEY_ID: ${{ secrets.CI_STAGE_AWS_ACCESS_KEY_ID }}
          CI_STAGE_AWS_SECRET_ACCESS_KEY: ${{ secrets.CI_STAGE_AWS_SECRET_ACCESS_KEY }}
      - uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: CITerraformRole
      - name: terraform apply
        uses: dflook/terraform-apply@v2
        with:
          path: ${{ env.terraform_dir }}
          # skip the terraform plan if running via workflow dispatch
          auto_approve: ${{ github.event_name == 'workflow_dispatch' }}
