name: Terraform Stuff
on:
  pull_request:
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform.yml'
jobs:
  terraform-stuff:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # note that the bootstrap dir is not included here, that's
        # because it isn't used much and as such it's on a really
        # old version of terraform
        terraform-dirs: [terraform/core, terraform/prod-1, terraform/stage-1]
    defaults:
      run:
        working-directory: ${{ matrix.terraform-dirs }}
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.CI_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CI_AWS_SECRET_ACCESS_KEY }}
          # role-to-assume: arn:aws:iam::704461573429:role/CIRole
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.5"
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check -diff
      - name: Terraform init
        run: terraform init
      - name: Terraform diff
        run: terraform diff
